In [1]:
# Siyu Xiao
# Nov 30, 2020
# Decision Tree

In [28]:
import pandas as pd
import numpy as np
from sklearn import tree
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelBinarizer
from sklearn.neural_network import MLPClassifier

In [4]:
pd.__version__

'1.2.3'

In [38]:
pd.__version__

'0.25.3'

In [5]:
import sys
print(sys.version)

3.9.4 (v3.9.4:1f2e3088f3, Apr  4 2021, 12:32:44) 
[Clang 6.0 (clang-600.0.57)]


In [6]:
from platform import python_version
print(python_version())

3.9.4


In [7]:
train = pd.read_csv('train.csv')
train

age  cost_of_ad device_type gender  in_initial_launch_location  income  \
0      56    0.005737      iPhone      M                           0   62717   
1      50    0.004733     desktop      F                           0   64328   
2      54    0.004129      laptop      M                           0   83439   
3      16    0.005117     Android      F                           0   30110   
4      37    0.003635     desktop      M                           0   76565   
...   ...         ...         ...    ...                         ...     ...   
9995   41    0.004225     desktop      M                           0   64489   
9996   50    0.004751       other      F                           0   88643   
9997   60    0.003804       other      M                           0   87870   
9998   18    0.003838      laptop      M                           0   56468   
9999   33    0.005250      iPhone    NaN                           0   59935   

      n_drivers  n_vehicles  prior_ins_tenure  outcome  
0             2           1                 4        0  
1             2           3                 2        0  
2             1           3                 7        0  
3             2           3                 0        0  
4             2           1                 5        0  
...         ...         ...               ...      ...  
9995          2           3                 8        0  
9996          1           3                 0        0  
9997          2           2                 9        0  
9998          2           2                 0        0  
9999          2           1                 6        0  

[10000 rows x 10 columns]

In [8]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   age                         10000 non-null  int64  
 1   cost_of_ad                  10000 non-null  float64
 2   device_type                 10000 non-null  object 
 3   gender                      9731 non-null   object 
 4   in_initial_launch_location  10000 non-null  int64  
 5   income                      10000 non-null  int64  
 6   n_drivers                   10000 non-null  int64  
 7   n_vehicles                  10000 non-null  int64  
 8   prior_ins_tenure            10000 non-null  int64  
 9   outcome                     10000 non-null  int64  
dtypes: float64(1), int64(7), object(2)
memory usage: 781.4+ KB


In [9]:
train_str_data = train[['device_type', 'gender']]
train_onehot = OneHotEncoder().fit_transform(train_str_data).toarray()
train_onehot.shape

(10000, 8)

In [10]:
train_num_data = train[['age', 'cost_of_ad', 'in_initial_launch_location', 'income', 'n_drivers', 'n_vehicles', 'prior_ins_tenure']].to_numpy()
train_num_data.shape

(10000, 7)

In [11]:
train_data = np.concatenate((train_onehot, train_num_data), axis=1)
train_data.shape

(10000, 15)

In [12]:
train_label = train[['outcome']]
train_label.shape

(10000, 1)

In [13]:
train_label

outcome
0           0
1           0
2           0
3           0
4           0
...       ...
9995        0
9996        0
9997        0
9998        0
9999        0

[10000 rows x 1 columns]

In [14]:
train_label.value_counts()

outcome
0          9018
1           982
dtype: int64

In [15]:
dtc = tree.DecisionTreeClassifier(criterion="entropy")
clf = dtc.fit(train_data, train_label)

In [16]:
test = pd.read_csv('test.csv')
test_str_data = test[['device_type', 'gender']]
test_onehot = OneHotEncoder().fit_transform(test_str_data).toarray()
test_num_data = test[['age', 'cost_of_ad', 'in_initial_launch_location', 'income', 'n_drivers', 'n_vehicles', 'prior_ins_tenure']].to_numpy()
test_data = np.concatenate((test_onehot, test_num_data), axis=1)

In [17]:
test_data

array([[ 1.,  0.,  0., ...,  1.,  3.,  7.],
       [ 0.,  1.,  0., ...,  1.,  1., 11.],
       [ 0.,  0.,  0., ...,  1.,  1.,  4.],
       ...,
       [ 0.,  0.,  1., ...,  1.,  2.,  3.],
       [ 0.,  0.,  0., ...,  1.,  1.,  9.],
       [ 0.,  0.,  0., ...,  2.,  1.,  1.]])

In [27]:
predict = clf.predict_proba(test_data)
predict

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [43]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier().fit(train_data, train_label.to_numpy().ravel())

In [51]:
predict = clf.predict_proba(test_data)
predict[:10]

array([[1.00000000e+000, 7.67416415e-135],
       [1.00000000e+000, 3.63338302e-279],
       [1.00000000e+000, 7.89593229e-263],
       [1.00000000e+000, 6.60654879e-209],
       [1.00000000e+000, 2.20289244e-121],
       [1.00000000e+000, 1.93334285e-202],
       [1.00000000e+000, 4.92909329e-194],
       [1.00000000e+000, 9.06865500e-124],
       [1.00000000e+000, 2.89780741e-150],
       [1.00000000e+000, 1.16679333e-240]])